DROP TABLE IF EXISTS abilities CASCADE;
CREATE TABLE abilities(
  id serial primary key,
  ability varchar,
  abilityi varchar,
);

DROP TABLE IF EXISTS brands CASCADE;
CREATE TABLE brands(
  id serial primary key,
  brand varchar,
  brandi varchar,
  pref varchar,
  unpref varchar,
);

DROP TABLE IF EXISTS gear CASCADE;
CREATE TABLE gear(
  id serial primary key,
--name
  gearname varchar,
--image links
  geari varchar,
--ability data
  brand varchar,
  main varchar,
  
--color
  color1 varchar,
  color2 varchar,
--owner
  annieshop boolean
--type
  catagory varchar,
  winter boolean,
  spring boolean,
  summer boolean,
  fall boolean,
--misc
  costig integer,
  rarity integer,
);

INSERT INTO gear VALUES
(DEFAULT,"18K Aviators", "",
                "Rockenberg", "Last-Ditch Effort", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                12000, 0),
(DEFAULT,"Annaki Beret", "",
                "Annaki", "Ink Resistance Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                11500, 0),
(DEFAULT,"Annaki Mask", "",
                "Annaki", "Opening Gambit", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                3600, 0),
(DEFAULT,"Armor Helmet Replica", "",
                "Cuttlegear", "Tenacity", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Backwards Cap", "",
                "Zekko", "Quick Respawn", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                700, 0),
(DEFAULT,"Bamboo Hat", "",
                "Inkline", "Ink Saver (Main)", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                2200, 0),
(DEFAULT,"B-ball Headband", "",
                "Zink", "Opening Gambit", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                300, 0),
(DEFAULT,"Bike Helmet", "",
                "Skalop", "Ink Recovery Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                4800, 0),
(DEFAULT,"Black Arrowbands", "",
                "Zekko", "Tenacity", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                2800, 0),
(DEFAULT,"Blowfish Bell Hat", "",
                "Firefin", "Ink Recovery Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                850, 0),
(DEFAULT,"Bobble Hat", "",
                "Splash Mob", "Quick Super Jump", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                2000, 0),
(DEFAULT,"Bucket Hat", "",
                "SquidForce", "Special Saver", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                400, 0),
(DEFAULT,"Camo Mesh", "",
                "Firefin", "Swim Speed Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                1400, 0),
(DEFAULT,"Camping Hat", "",
                "Inkline", "Special Power Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                800, 0),
(DEFAULT,"Classic Straw Boater", "",
                "Skalop", "Special Power Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                1500, 0),
(DEFAULT,"Cycle King Cap", "",
                "Tentatek", "Bomb Defense Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                2400, 0),
(DEFAULT,"Cycling Cap", "",
                "Zink", "Sub Power Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                800, 0),
(DEFAULT,"Designer Headphones", "",
                "Forge", "Ink Saver (Sub)", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                2500, 0),
(DEFAULT,"Double Egg Shades", "",
                "Zekko", "Run Speed Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                2200, 0),
(DEFAULT,"Dust Blocker 2000", "",
                "Grizzco", "", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Eminence Cuff", "",
                "Enperry", "Ink Saver (Main)", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Face Visor", "",
                "Toni Kensa", "Bomb Defense Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                10300, 0),
(DEFAULT,"Fake Contacts", "",
                "Tentatek", "Special Charge Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                2000, 0),
(DEFAULT,"Firefin Facemask", "",
                "Firefin", "Run Speed Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                650, 0),
(DEFAULT,"FishFry Biscuit Bandana", "",
                "Firefin", "Special Power Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                1250, 0),
(DEFAULT,"FishFry Visor", "",
                "Firefin", "Special Charge Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                500, 0),
(DEFAULT,"Five-Panel Cap", "",
                "Zekko", "Comeback", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                1800, 0),
(DEFAULT,"Forge Mask", "",
                "Forge", "Cold-Blooded", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                1400, 0),
(DEFAULT,"Fugu Bell Hat", "",
                "Firefin", "Quick Respawn", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                1700, 0),
(DEFAULT,"Full Moon Glasses", "",
                "Krak-On", "Quick Super Jump", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                600, 0),
(DEFAULT,"Half-Rim Glasses", "",
                "Splash Mob", "Special Power Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                4100, 0),
(DEFAULT,"Headlamp Helmet", "",
                "Grizzco", "", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Hero Headphones Replica", "",
                "Cuttlegear", "Special Saver", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Hero Headset Replica", "",
                "Cuttlegear", "Run Speed Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Hickory Work Cap", "",
                "Krak-On", "Special Power Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                8700, 0),
(DEFAULT,"Hockey Helmet", "",
                "Forge", "Cold-Blooded", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                9900, 0),
(DEFAULT,"House-Tag Denim Cap", "",
                "Splash Mob", "Special Charge Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                5200, 0),
(DEFAULT,"Jellyvader Cap", "",
                "Skalop", "Ink Saver (Sub)", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                10000, 0),
(DEFAULT,"Jet Cap", "",
                "Firefin", "Special Saver", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                700, 0),
(DEFAULT,"Jungle Hat", "",
                "Firefin", "Ink Saver (Main)", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                9000, 0),
(DEFAULT,"King Facemask", "",
                "Enperry", "Ink Saver (Sub)", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                500, 0),
(DEFAULT,"King Flip Mesh", "",
                "Enperry", "Run Speed Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                3200, 0),
(DEFAULT,"Knitted Hat", "",
                "Firefin", "Ink Resistance Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                1400, 0),
(DEFAULT,"Lightweight Cap", "",
                "Inkline", "Swim Speed Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                800, 0),
(DEFAULT,"Matte Bike Helmet", "",
                "Zekko", "Sub Power Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                10000, 0),
(DEFAULT,"Moist Ghillie Helmet", "",
                "Forge", "Run Speed Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                8500, 0),
(DEFAULT,"Motocross Nose Guard", "",
                "Forge", "Special Charge Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                7600, 0),
(DEFAULT,"MTB Helmet", "",
                "Zekko", "Tenacity", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                10500, 0),
(DEFAULT,"Noise Cancelers", "",
                "Forge", "Quick Respawn", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                9200, 0),
(DEFAULT,"Paintball Mask", "",
                "Forge", "Comeback", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                10000, 0),
(DEFAULT,"Painter's Mask", "",
                "SquidForce", "Cold-Blooded", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                4500, 0),
(DEFAULT,"Paisley Bandana", "",
                "Krak-On", "Ink Saver (Sub)", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                750, 0),
(DEFAULT,"Patched Hat", "",
                "Skalop", "Cold-Blooded", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                3600, 0),
(DEFAULT,"Pilot Goggles", "",
                "Forge", "Sub Power Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                5500, 0),
(DEFAULT,"Power Mask", "",
                "amiibo", "Bomb Defense Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Power Mask Mk I", "",
                "amiibo", "Ink Resistance Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Retro Specs", "",
                "Splash Mob", "Quick Respawn", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                500, 0),
(DEFAULT,"Safari Hat", "",
                "Forge", "Last-Ditch Effort", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                2300, 0),
(DEFAULT,"Samurai Helmet", "",
                "amiibo", "Quick Super Jump", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Short Beanie", "",
                "Inkline", "Ink Saver (Main)", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                600, 0),
(DEFAULT,"Skate Helmet", "",
                "Skalop", "Special Saver", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                2500, 0),
(DEFAULT,"Skull Bandana", "",
                "Forge", "Special Saver", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                7800, 0),
(DEFAULT,"Sneaky Beanie", "",
                "Skalop", "Swim Speed Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                3000, 0),
(DEFAULT,"Snorkel Mask", "",
                "Forge", "Ink Saver (Sub)", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                3000, 0),
(DEFAULT,"Soccer Headband", "",
                "Tentatek", "Tenacity", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                3000, 0),
(DEFAULT,"Special Forces Beret", "",
                "Forge", "Opening Gambit", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                9700, 0),
(DEFAULT,"Splash Goggles", "",
                "Forge", "Bomb Defense Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                2800, 0),
(DEFAULT,"Sporty Bobble Hat", "",
                "Skalop", "Tenacity", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                800, 0),
(DEFAULT,"Squash Headband", "",
                "Zink", "Special Saver", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                400, 0),
(DEFAULT,"Squid Clip-Ons", "",
                "amiibo", "Opening Gambit", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Squid Facemask", "",
                "SquidForce", "Ink Saver (Main)", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                300, 0),
(DEFAULT,"Squid Hairclip", "",
                "amiibo", "Swim Speed Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Squidfin Hook Cans", "",
                "Forge", "Ink Resistance Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                3800, 0),
(DEFAULT,"Squidlife Headphones", "",
                "Forge", "Ink Recovery Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                7070, 0),
(DEFAULT,"Squidvader Cap", "",
                "Skalop", "Special Charge Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                1300, 0),
(DEFAULT,"Squinja Mask", "",
                "amiibo", "Quick Respawn", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Stealth Goggles", "",
                "Forge", "Swim Speed Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                9800, 0),
(DEFAULT,"Straw Boater", "",
                "Skalop", "Quick Super Jump", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                550, 0),
(DEFAULT,"Streetstyle Cap", "",
                "Skalop", "Ink Saver (Sub)", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                600, 0),
(DEFAULT,"Striped Beanie", "",
                "Splash Mob", "Opening Gambit", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                900, 0),
(DEFAULT,"Studio Headphones", "",
                "Forge", "Ink Saver (Main)", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                2800, 0),
(DEFAULT,"Sun Visor", "",
                "Tentatek", "Sub Power Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                2600, 0),
(DEFAULT,"Takoroka Mesh", "",
                "Takoroka", "Bomb Defense Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                400, 0),
(DEFAULT,"Takoroka Visor", "",
                "Takoroka", "Quick Super Jump", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                7500, 0),
(DEFAULT,"Tennis Headband", "",
                "Tentatek", "Comeback", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                300, 0),
(DEFAULT,"Tinted Shades", "",
                "Zekko", "Last-Ditch Effort", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                350, 0),
(DEFAULT,"Treasure Hunter", "",
                "Forge", "Ink Recovery Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                3000, 0),
(DEFAULT,"Tulip Parasol", "",
                "Inkline", "Ink Resistance Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                1280, 0),
(DEFAULT,"Two-Stripe Mesh", "",
                "Krak-On", "Special Saver", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                700, 0),
(DEFAULT,"Urchins Cap", "",
                "Skalop", "Sub Power Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                600, 0),
(DEFAULT,"Visor Skate Helmet", "",
                "Skalop", "Last-Ditch Effort", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                8000, 0),
(DEFAULT,"White Headband", "",
                "SquidForce", "Ink Recovery Up", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                , 0),
(DEFAULT,"Woolly Urchins Classic", "",
                "Krak-On", "Comeback", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                3800, 0),
(DEFAULT,"Yamagiri Beanie", "",
                "Inkline", "Cold-Blooded", "...", "...",
                "F","Headgear",
                "-","-","-","-",
                1280, 0),
(DEFAULT,"Acerola Rain Boots", "",
                "Inkline", "Run Speed Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                600, 0),
(DEFAULT,"Amber Sea Slug Hi-Tops", "",
                "Tentatek", "Drop Roller", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                11000, 0),
(DEFAULT,"Angry Rain Boots", "",
                "Grizzco", "", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Annaki Habaneros", "",
                "Annaki", "Sub Power Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                8800, 0),
(DEFAULT,"Armor Boot Replicas", "",
                "Cuttlegear", "Ink Saver (Main)", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Arrow Pull-Ons", "",
                "Toni Kensa", "Drop Roller", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                10000, 0),
(DEFAULT,"Birch Climbing Shoes", "",
                "Inkline", "Special Charge Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1200, 0),
(DEFAULT,"Black Dakroniks", "",
                "Zink", "Cold-Blooded", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1500, 0),
(DEFAULT,"Black Flip-Flops", "",
                "Zekko", "Object Shredder", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                300, 0),
(DEFAULT,"Black Norimaki 750s", "",
                "Tentatek", "Special Charge Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                9800, 0),
(DEFAULT,"Black Seahorses", "",
                "Zink", "Swim Speed Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                2000, 0),
(DEFAULT,"Black Trainers", "",
                "Tentatek", "Quick Respawn", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                500, 0),
(DEFAULT,"Blue & Black Squidkid IV", "",
                "Enperry", "Quick Super Jump", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                11000, 0),
(DEFAULT,"Blue Laceless Dakroniks", "",
                "Zink", "Stealth Jump", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1400, 0),
(DEFAULT,"Blue Lo-Tops", "",
                "Zekko", "Bomb Defense Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                800, 0),
(DEFAULT,"Blue Moto Boots", "",
                "Rockenberg", "Ink Resistance Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                10800, 0),
(DEFAULT,"Blue Slip-Ons", "",
                "Krak-On", "Sub Power Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                400, 0),
(DEFAULT,"Blueberry Casuals", "",
                "Krak-On", "Ink Saver (Sub)", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                700, 0),
(DEFAULT,"Bubble Rain Boots", "",
                "Inkline", "Drop Roller", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                450, 0),
(DEFAULT,"Canary Trainers", "",
                "Tentatek", "Quick Super Jump", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                900, 0),
(DEFAULT,"Cherry Kicks", "",
                "Rockenberg", "Stealth Jump", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                2400, 0),
(DEFAULT,"Choco Clogs", "",
                "Krak-On", "Quick Respawn", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1800, 0),
(DEFAULT,"Clownfish Basics", "",
                "Krak-On", "Special Charge Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                500, 0),
(DEFAULT,"Crazy Arrows", "",
                "Takoroka", "Stealth Jump", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                4500, 0),
(DEFAULT,"Cream Basics", "",
                "Krak-On", "Special Saver", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                , 0),
(DEFAULT,"Cyan Trainers", "",
                "Tentatek", "Stealth Jump", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                700, 0),
(DEFAULT,"Deepsea Leather Boots", "",
                "Rockenberg", "Ink Saver (Sub)", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                12000, 0),
(DEFAULT,"Fringed Loafers", "",
                "amiibo", "Cold-Blooded", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Gold Hi-Horses", "",
                "Zink", "Run Speed Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                7000, 0),
(DEFAULT,"Gray Sea-Slug Hi-Tops", "",
                "Tentatek", "Bomb Defense Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                8500, 0),
(DEFAULT,"Gray Yellow-Soled Wingtips", "",
                "Rockenberg", "Quick Super Jump", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                4600, 0),
(DEFAULT,"Green Iromaki 750s", "",
                "Tentatek", "Special Power Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1050, 0),
(DEFAULT,"Green Laceups", "",
                "Splash Mob", "Cold-Blooded", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1300, 0),
(DEFAULT,"Green Rain Boots", "",
                "Inkline", "Stealth Jump", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1600, 0),
(DEFAULT,"Hero Runner Replicas", "",
                "Cuttlegear", "Quick Super Jump", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Hero Snowboots Replicas", "",
                "Cuttlegear", "Ink Saver (Sub)", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Hunter Hi-Tops", "",
                "Krak-On", "Ink Recovery Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                500, 0),
(DEFAULT,"Hunting Boots", "",
                "Splash Mob", "Bomb Defense Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                11500, 0),
(DEFAULT,"Kid Clams", "",
                "Rockenberg", "Special Power Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                9500, 0),
(DEFAULT,"LE Soccer Shoes", "",
                "Takoroka", "Ink Resistance Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                7500, 0),
(DEFAULT,"Luminous Delta Straps", "",
                "Inkline", "Cold-Blooded", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                5000, 0),
(DEFAULT,"Mawcasins", "",
                "Splash Mob", "Ink Recovery Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                2400, 0),
(DEFAULT,"Milky Enperrials", "",
                "Enperry", "Swim Speed Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Mint Dakroniks", "",
                "Zink", "Drop Roller", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1200, 0),
(DEFAULT,"Moist Ghillie Boots", "",
                "Forge", "Object Shredder", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                8500, 0),
(DEFAULT,"Moto Boots", "",
                "Rockenberg", "Quick Respawn", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                3800, 0),
(DEFAULT,"Navy Enperrials", "",
                "Enperry", "Ink Saver (Main)", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                11000, 0),
(DEFAULT,"Navy Red-Soled Wingtips", "",
                "Rockenberg", "Ink Saver (Main)", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                4600, 0),
(DEFAULT,"Neon Delta Straps", "",
                "Inkline", "Sub Power Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                4800, 0),
(DEFAULT,"Neon Sea Slugs", "",
                "Tentatek", "Ink Resistance Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                700, 0),
(DEFAULT,"N-Pacer Ag", "",
                "Enperry", "Ink Recovery Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                4900, 0),
(DEFAULT,"N-Pacer Au", "",
                "Enperry", "Quick Respawn", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                8900, 0),
(DEFAULT,"Orange Arrows", "",
                "Takoroka", "Ink Saver (Main)", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1100, 0),
(DEFAULT,"Orca Hi-Tops", "",
                "Takoroka", "Special Saver", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                2800, 0),
(DEFAULT,"Orca Woven Hi-Tops", "",
                "Takoroka", "Ink Saver (Sub)", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                3600, 0),
(DEFAULT,"Oyster Clogs", "",
                "Krak-On", "Run Speed Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                600, 0),
(DEFAULT,"Pink Trainers", "",
                "Tentatek", "Sub Power Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                500, 0),
(DEFAULT,"Piranha Moccasins", "",
                "Splash Mob", "Stealth Jump", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                9400, 0),
(DEFAULT,"Plum Casuals", "",
                "Krak-On", "Object Shredder", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                2000, 0),
(DEFAULT,"Polka-dot Slip-Ons", "",
                "Krak-On", "Drop Roller", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1500, 0),
(DEFAULT,"Power Boots", "",
                "amiibo", "Ink Saver (Main)", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Power Boots Mk I", "",
                "amiibo", "Bomb Defense Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Pro Trail Boots", "",
                "Inkline", "Ink Resistance Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                9800, 0),
(DEFAULT,"Punk Blacks", "",
                "Rockenberg", "Cold-Blooded", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                8800, 0),
(DEFAULT,"Punk Cherries", "",
                "Rockenberg", "Bomb Defense Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                9000, 0),
(DEFAULT,"Punk Whites", "",
                "Rockenberg", "Special Charge Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                3800, 0),
(DEFAULT,"Purple Hi-Horses", "",
                "Zink", "Special Power Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1000, 0),
(DEFAULT,"Purple Iromaki 750s", "",
                "Tentatek", "Swim Speed Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1050, 0),
(DEFAULT,"Purple Sea Slugs", "",
                "Tentatek", "Run Speed Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1800, 0),
(DEFAULT,"Red & Black Squidkid IV", "",
                "Enperry", "Special Charge Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                11000, 0),
(DEFAULT,"Red FishFry Sandals", "",
                "Firefin", "Object Shredder", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                2880, 0),
(DEFAULT,"Red Hi-Horses", "",
                "Zink", "Ink Saver (Main)", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                800, 0),
(DEFAULT,"Red Hi-Tops", "",
                "Krak-On", "Ink Resistance Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1800, 0),
(DEFAULT,"Red Iromaki 750s", "",
                "Tentatek", "Ink Saver (Sub)", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1050, 0),
(DEFAULT,"Red Sea Slugs", "",
                "Tentatek", "Special Saver", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                8000, 0),
(DEFAULT,"Red Slip-Ons", "",
                "Krak-On", "Quick Super Jump", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                300, 0),
(DEFAULT,"Red-Mesh Sneakers", "",
                "Tentatek", "Special Power Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1700, 0),
(DEFAULT,"Roasted Brogues", "",
                "Rockenberg", "Bomb Defense Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1200, 0),
(DEFAULT,"Samurai Shoes", "",
                "amiibo", "Special Power Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"School Shoes", "",
                "amiibo", "Ink Saver (Sub)", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Shark Moccasins", "",
                "Splash Mob", "Sub Power Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                800, 0),
(DEFAULT,"Smoky Wingtips", "",
                "Rockenberg", "Object Shredder", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                8600, 0),
(DEFAULT,"Snow Delta Straps", "",
                "Inkline", "Swim Speed Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                8800, 0),
(DEFAULT,"Snowy Down Boots", "",
                "Tentatek", "Quick Super Jump", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                8000, 0),
(DEFAULT,"Soccer Shoes", "",
                "Takoroka", "Bomb Defense Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                9600, 0),
(DEFAULT,"Squid-Stitch Slip-Ons", "",
                "Krak-On", "Bomb Defense Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1500, 0),
(DEFAULT,"Squinja Boots", "",
                "amiibo", "Swim Speed Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Squink Wingtips", "",
                "Rockenberg", "Quick Respawn", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                800, 0),
(DEFAULT,"Strapping Reds", "",
                "Splash Mob", "Ink Resistance Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1400, 0),
(DEFAULT,"Strapping Whites", "",
                "Splash Mob", "Ink Saver (Sub)", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                8700, 0),
(DEFAULT,"Sun & Shade Squidkid IV", "",
                "Enperry", "Cold-Blooded", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                13000, 0),
(DEFAULT,"Sunny Climbing Shoes", "",
                "Inkline", "Special Saver", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                3200, 0),
(DEFAULT,"Sunset Orca Hi-Tops", "",
                "Takoroka", "Drop Roller", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                3800, 0),
(DEFAULT,"Tan Work Boots", "",
                "Rockenberg", "Sub Power Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                3000, 0),
(DEFAULT,"Trail Boots", "",
                "Inkline", "Ink Recovery Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                7500, 0),
(DEFAULT,"Turquoise Kicks", "",
                "Rockenberg", "Special Charge Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                2800, 0),
(DEFAULT,"Violet Trainers", "",
                "Tentatek", "Object Shredder", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1000, 0),
(DEFAULT,"White Arrows", "",
                "Takoroka", "Special Power Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                2500, 0),
(DEFAULT,"White Kicks", "",
                "Rockenberg", "Swim Speed Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1400, 0),
(DEFAULT,"White Laceless Dakroniks", "",
                "Zink", "Run Speed Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1800, 0),
(DEFAULT,"White Norimaki 750s", "",
                "Tentatek", "Swim Speed Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                3800, 0),
(DEFAULT,"White Seahorses", "",
                "Zink", "Ink Recovery Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                600, 0),
(DEFAULT,"Yellow Iromaki 750s", "",
                "Tentatek", "Special Saver", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1050, 0),
(DEFAULT,"Yellow-Mesh Sneakers", "",
                "Tentatek", "Cold-Blooded", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                1300, 0),
(DEFAULT,"Zombie Hi-Horses", "",
                "Zink", "Special Charge Up", "...", "...",
                "F","Shoes",
                "-","-","-","-",
                800, 0),
(DEFAULT,"Aloha Shirt", "",
                "Forge", "Ink Recovery Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                700, 0),
(DEFAULT,"Anchor Life Vest", "",
                "Grizzco", "", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Anchor Sweat", "",
                "SquidForce", "Cold-Blooded", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2800, 0),
(DEFAULT,"Annaki Blue Cuff", "",
                "Annaki", "Special Saver", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                4800, 0),
(DEFAULT,"Annaki Drive Tee", "",
                "Annaki", "Thermal Ink", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                5500, 0),
(DEFAULT,"Annaki Evolution Tee", "",
                "Annaki", "Respawn Punisher", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                8800, 0),
(DEFAULT,"Annaki Red Cuff", "",
                "Annaki", "Haunt", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                4800, 0),
(DEFAULT,"Armor Jacket Replica", "",
                "Cuttlegear", "Special Charge Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Baby-Jelly Shirt", "",
                "Splash Mob", "Bomb Defense Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1350, 0),
(DEFAULT,"Baby-Jelly Shirt & Tie", "",
                "Splash Mob", "Cold-Blooded", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                3800, 0),
(DEFAULT,"Baseball Jersey", "",
                "Firefin", "Special Charge Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                10000, 0),
(DEFAULT,"Basic Tee", "",
                "SquidForce", "Quick Respawn", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                , 0),
(DEFAULT,"B-ball Jersey (Away)", "",
                "Zink", "Ink Saver (Sub)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                800, 0),
(DEFAULT,"B-ball Jersey (Home)", "",
                "Zink", "Special Saver", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2300, 0),
(DEFAULT,"Berry Ski Jacket", "",
                "Inkline", "Special Power Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                3900, 0),
(DEFAULT,"Birded Corduroy Jacket", "",
                "Zekko", "Run Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                10400, 0),
(DEFAULT,"Black 8-Bit FishFry", "",
                "Firefin", "Bomb Defense Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                600, 0),
(DEFAULT,"Black Anchor Tee", "",
                "SquidForce", "Respawn Punisher", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2800, 0),
(DEFAULT,"Black Baseball LS", "",
                "Rockenberg", "Swim Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                800, 0),
(DEFAULT,"Black Inky Rider", "",
                "Rockenberg", "Sub Power Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                12100, 0),
(DEFAULT,"Black LS", "",
                "Zekko", "Quick Super Jump", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                3000, 0),
(DEFAULT,"Black Polo", "",
                "Zekko", "Ninja Squid", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                500, 0),
(DEFAULT,"Black Squideye", "",
                "Tentatek", "Run Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                500, 0),
(DEFAULT,"Black Tee", "",
                "SquidForce", "Special Power Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                400, 0),
(DEFAULT,"Black Urchin Rock Tee", "",
                "Rockenberg", "Ink Recovery Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                850, 0),
(DEFAULT,"Black V-Neck Tee", "",
                "SquidForce", "Thermal Ink", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                3800, 0),
(DEFAULT,"Blue Peaks Tee", "",
                "Inkline", "Ink Saver (Sub)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                400, 0),
(DEFAULT,"Blue Sailor Suit", "",
                "Forge", "Sub Power Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                11000, 0),
(DEFAULT,"Blue Tentatek Tee", "",
                "Tentatek", "Quick Respawn", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                3100, 0),
(DEFAULT,"Brown FA-11 Bomber", "",
                "Forge", "Bomb Defense Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Camo Zip Hoodie", "",
                "Firefin", "Quick Respawn", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                9000, 0),
(DEFAULT,"Carnivore Tee", "",
                "Firefin", "Bomb Defense Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                500, 0),
(DEFAULT,"Chilly Mountain Coat", "",
                "Inkline", "Swim Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                7900, 0),
(DEFAULT,"Chirpy Chips Band Tee", "",
                "Rockenberg", "Cold-Blooded", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                900, 0),
(DEFAULT,"Choco Layered LS", "",
                "Takoroka", "Ink Saver (Sub)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1400, 0),
(DEFAULT,"Crimson Parashooter", "",
                "Annaki", "Special Charge Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                9200, 0),
(DEFAULT,"Custom Painted F-3", "",
                "Forge", "Ink Resistance Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                9700, 0),
(DEFAULT,"Cycle King Jersey", "",
                "Tentatek", "Bomb Defense Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                8900, 0),
(DEFAULT,"Cycling Shirt", "",
                "Zink", "Cold-Blooded", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2900, 0),
(DEFAULT,"Dark Bomber Jacket", "",
                "Toni Kensa", "Special Power Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                12800, 0),
(DEFAULT,"Dark Urban Vest", "",
                "Firefin", "Cold-Blooded", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                10000, 0),
(DEFAULT,"Eggplant Mountain Coat", "",
                "Inkline", "Special Saver", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                7600, 0),
(DEFAULT,"FA-01 Jacket", "",
                "Forge", "Ink Recovery Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                10100, 0),
(DEFAULT,"FA-01 Reversed", "",
                "Forge", "Quick Super Jump", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                10100, 0),
(DEFAULT,"FC Albacore", "",
                "Takoroka", "Respawn Punisher", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1200, 0),
(DEFAULT,"Firefin Navy Sweat", "",
                "Firefin", "Sub Power Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2500, 0),
(DEFAULT,"Firewave Tee", "",
                "Skalop", "Special Charge Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1250, 0),
(DEFAULT,"Fishing Vest", "",
                "Inkline", "Quick Respawn", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                4200, 0),
(DEFAULT,"Forge Inkling Parka", "",
                "Forge", "Run Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2900, 0),
(DEFAULT,"Front Zip Vest", "",
                "Toni Kensa", "Ink Resistance Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                5500, 0),
(DEFAULT,"Fugu Tee", "",
                "Firefin", "Swim Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                750, 0),
(DEFAULT,"Garden Gear", "",
                "Grizzco", "", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Grape Hoodie", "",
                "Enperry", "Quick Respawn", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1100, 0),
(DEFAULT,"Grape Tee", "",
                "Skalop", "Ink Recovery Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                400, 0),
(DEFAULT,"Gray 8-Bit FishFry", "",
                "Firefin", "Special Charge Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                800, 0),
(DEFAULT,"Gray College Sweat", "",
                "Splash Mob", "Swim Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                800, 0),
(DEFAULT,"Gray FA-11 Bomber", "",
                "Forge", "Cold-Blooded", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Gray Hoodie", "",
                "Skalop", "Sub Power Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1900, 0),
(DEFAULT,"Gray Mixed Shirt", "",
                "Zekko", "Quick Super Jump", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2800, 0),
(DEFAULT,"Green Striped LS", "",
                "Inkline", "Ninja Squid", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                700, 0),
(DEFAULT,"Green Tee", "",
                "Forge", "Special Saver", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1200, 0),
(DEFAULT,"Green V-Neck Limited Tee", "",
                "SquidForce", "Quick Super Jump", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Green Zip Hoodie", "",
                "Firefin", "Special Power Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2800, 0),
(DEFAULT,"Green-Check Shirt", "",
                "Zekko", "Sub Power Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2000, 0),
(DEFAULT,"Half-Sleeve Sweater", "",
                "Toni Kensa", "Ink Saver (Sub)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                4100, 0),
(DEFAULT,"Hero Hoodie Replica", "",
                "Cuttlegear", "Ink Recovery Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Hero Jacket Replica", "",
                "Cuttlegear", "Swim Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Hightide Era Band Tee", "",
                "Rockenberg", "Thermal Ink", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                900, 0),
(DEFAULT,"Hula Punk Shirt", "",
                "Annaki", "Ink Saver (Main)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                5000, 0),
(DEFAULT,"Icewave Tee", "",
                "Skalop", "Ninja Squid", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1250, 0),
(DEFAULT,"Inkfall Shirt", "",
                "Toni Kensa", "Special Charge Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                4900, 0),
(DEFAULT,"Inkopolis Squaps Jersey", "",
                "Zink", "Cold-Blooded", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1250, 0),
(DEFAULT,"Juice Parka", "",
                "Grizzco", "", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Kensa Coat", "",
                "Toni Kensa", "Respawn Punisher", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                9200, 0),
(DEFAULT,"King Jersey", "",
                "Enperry", "Respawn Punisher", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                3100, 0),
(DEFAULT,"Krak-On 528", "",
                "Krak-On", "Run Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                800, 0),
(DEFAULT,"Layered Anchor LS", "",
                "SquidForce", "Run Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                4000, 0),
(DEFAULT,"Layered Vector LS", "",
                "Takoroka", "Special Saver", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1200, 0),
(DEFAULT,"Light Bomber Jacket", "",
                "Toni Kensa", "Quick Super Jump", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                12800, 0),
(DEFAULT,"Lime Easy-Stripe Shirt", "",
                "Splash Mob", "Ink Resistance Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                3800, 0),
(DEFAULT,"Linen Shirt", "",
                "Splash Mob", "Sub Power Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                700, 0),
(DEFAULT,"Logo Aloha Shirt", "",
                "Zekko", "Ink Recovery Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2900, 0),
(DEFAULT,"Lumberjack Shirt", "",
                "Rockenberg", "Ink Saver (Main)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                800, 0),
(DEFAULT,"Matcha Down Jacket", "",
                "Inkline", "Ninja Squid", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                9100, 0),
(DEFAULT,"Milky Eminence Jacket", "",
                "Enperry", "Run Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Mint Tee", "",
                "Skalop", "Bomb Defense Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                400, 0),
(DEFAULT,"Mister Shrug Tee", "",
                "Krak-On", "Ink Resistance Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                9200, 0),
(DEFAULT,"Moist Ghillie Suit", "",
                "Forge", "Ink Saver (Sub)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                8500, 0),
(DEFAULT,"Mountain Vest", "",
                "Inkline", "Swim Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                11000, 0),
(DEFAULT,"Navy Deca Logo Tee", "",
                "Zink", "Ink Saver (Main)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1200, 0),
(DEFAULT,"Navy Eminence Jacket", "",
                "Enperry", "Ink Saver (Main)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                10500, 0),
(DEFAULT,"Navy King Tank", "",
                "Enperry", "Ink Resistance Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                600, 0),
(DEFAULT,"Navy Striped LS", "",
                "Splash Mob", "Ink Recovery Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1050, 0),
(DEFAULT,"Negative Longcuff Sweater", "",
                "Toni Kensa", "Haunt", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                11800, 0),
(DEFAULT,"N-Pacer Sweat", "",
                "Enperry", "Thermal Ink", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                7800, 0),
(DEFAULT,"Octobowler Shirt", "",
                "Krak-On", "Ink Saver (Main)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2100, 0),
(DEFAULT,"Olive Ski Jacket", "",
                "Inkline", "Run Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                11000, 0),
(DEFAULT,"Olive Zekko Parka", "",
                "Zekko", "Swim Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                3800, 0),
(DEFAULT,"Orange Cardigan", "",
                "Splash Mob", "Special Charge Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                700, 0),
(DEFAULT,"Part-Time Pirate", "",
                "Tentatek", "Respawn Punisher", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                800, 0),
(DEFAULT,"Pearl Tee", "",
                "Skalop", "Ink Saver (Sub)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                400, 0),
(DEFAULT,"Pink Easy-Stripe Shirt", "",
                "Splash Mob", "Quick Super Jump", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                3800, 0),
(DEFAULT,"Pink Hoodie", "",
                "Splash Mob", "Bomb Defense Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                3400, 0),
(DEFAULT,"Pirate-Stripe Tee", "",
                "Splash Mob", "Special Power Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                700, 0),
(DEFAULT,"Positive Longcuff Sweater", "",
                "Toni Kensa", "Swim Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                10800, 0),
(DEFAULT,"Power Armor", "",
                "amiibo", "Quick Respawn", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Power Armor Mk I", "",
                "amiibo", "Ink Resistance Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Prune Parashooter", "",
                "Annaki", "Ninja Squid", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                7800, 0),
(DEFAULT,"Pullover Coat", "",
                "Toni Kensa", "Thermal Ink", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                13200, 0),
(DEFAULT,"Purple Camo LS", "",
                "Takoroka", "Sub Power Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                600, 0),
(DEFAULT,"Rainy-Day Tee", "",
                "Krak-On", "Ink Saver (Main)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                300, 0),
(DEFAULT,"Red Hula Punk with Tie", "",
                "Annaki", "Ink Resistance Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                9000, 0),
(DEFAULT,"Red Tentatek Tee", "",
                "Tentatek", "Swim Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                3100, 0),
(DEFAULT,"Red Vector Tee", "",
                "Takoroka", "Ink Saver (Main)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                500, 0),
(DEFAULT,"Red V-Neck Limited Tee", "",
                "SquidForce", "Quick Respawn", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Reel Sweat", "",
                "Zekko", "Special Power Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                900, 0),
(DEFAULT,"Reggae Tee", "",
                "Skalop", "Special Saver", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                8200, 0),
(DEFAULT,"Retro Sweat", "",
                "SquidForce", "Bomb Defense Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                9000, 0),
(DEFAULT,"Rockenberg White", "",
                "Rockenberg", "Ink Recovery Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2500, 0),
(DEFAULT,"Rodeo Shirt", "",
                "Krak-On", "Quick Super Jump", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                750, 0),
(DEFAULT,"Round-Collar Shirt", "",
                "Rockenberg", "Ink Saver (Sub)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1600, 0),
(DEFAULT,"Sage Polo", "",
                "Splash Mob", "Cold-Blooded", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                400, 0),
(DEFAULT,"Sailor-Stripe Tee", "",
                "Splash Mob", "Run Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                700, 0),
(DEFAULT,"Samurai Jacket", "",
                "amiibo", "Special Charge Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"School Cardigan", "",
                "amiibo", "Run Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"School Jersey", "",
                "Zink", "Ninja Squid", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                3000, 0),
(DEFAULT,"School Uniform", "",
                "amiibo", "Ink Recovery Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Shirt & Tie", "",
                "Splash Mob", "Special Saver", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                8400, 0),
(DEFAULT,"Shirt with Blue Hoodie", "",
                "Splash Mob", "Special Power Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2900, 0),
(DEFAULT,"Short Knit Layers", "",
                "Toni Kensa", "Ink Saver (Main)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                9850, 0),
(DEFAULT,"Shrimp-Pink Polo", "",
                "Splash Mob", "Ninja Squid", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                550, 0),
(DEFAULT,"Sky-Blue Squideye", "",
                "Tentatek", "Cold-Blooded", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                500, 0),
(DEFAULT,"Slash King Tank", "",
                "Enperry", "Thermal Ink", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                450, 0),
(DEFAULT,"Slipstream United", "",
                "Takoroka", "Bomb Defense Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1800, 0),
(DEFAULT,"Splatfest Tee", "",
                "SquidForce", "Ability Doubler", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Squid Satin Jacket", "",
                "Zekko", "Quick Respawn", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                9200, 0),
(DEFAULT,"Squid Squad Band Tee", "",
                "Rockenberg", "Ink Resistance Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                900, 0),
(DEFAULT,"Squiddor Polo", "",
                "Grizzco", "", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Squidmark LS", "",
                "SquidForce", "Haunt", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                600, 0),
(DEFAULT,"Squidmark Sweat", "",
                "SquidForce", "Sub Power Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                800, 0),
(DEFAULT,"Squidstar Waistcoat", "",
                "Krak-On", "Cold-Blooded", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                650, 0),
(DEFAULT,"Squinja Suit", "",
                "amiibo", "Special Saver", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                NULL, 0),
(DEFAULT,"Striped Shirt", "",
                "Splash Mob", "Quick Super Jump", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2200, 0),
(DEFAULT,"Sunny-Day Tee", "",
                "Krak-On", "Special Charge Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                300, 0),
(DEFAULT,"Takoroka Galactic Tie Dye", "",
                "Takoroka", "Thermal Ink", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                850, 0),
(DEFAULT,"Takoroka Nylon Vintage", "",
                "Takoroka", "Thermal Ink", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                9500, 0),
(DEFAULT,"Takoroka Rainbow Tie Dye", "",
                "Takoroka", "Quick Super Jump", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                850, 0),
(DEFAULT,"Takoroka Windcrusher", "",
                "Takoroka", "Cold-Blooded", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                8500, 0),
(DEFAULT,"Tentatek Slogan Tee", "",
                "Tentatek", "Special Charge Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1600, 0),
(DEFAULT,"Tricolor Rugby", "",
                "Takoroka", "Quick Respawn", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                700, 0),
(DEFAULT,"Tumeric Zekko Coat", "",
                "Zekko", "Thermal Ink", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                4600, 0),
(DEFAULT,"Urchins Jersey", "",
                "Zink", "Run Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                700, 0),
(DEFAULT,"Varsity Baseball LS", "",
                "Splash Mob", "Haunt", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                700, 0),
(DEFAULT,"Varsity Jacket", "",
                "Zekko", "Ink Saver (Sub)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                11500, 0),
(DEFAULT,"Vintage Check Shirt", "",
                "Rockenberg", "Haunt", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                9000, 0),
(DEFAULT,"Wet Floor Band Tee", "",
                "Rockenberg", "Swim Speed Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                900, 0),
(DEFAULT,"White 8-Bit FishFry", "",
                "Firefin", "Sub Power Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                800, 0),
(DEFAULT,"White Anchor Tee", "",
                "SquidForce", "Ninja Squid", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2800, 0),
(DEFAULT,"White Baseball LS", "",
                "Rockenberg", "Quick Super Jump", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                800, 0),
(DEFAULT,"White Deca Logo Tee", "",
                "Zink", "Ink Resistance Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1200, 0),
(DEFAULT,"White Inky Rider", "",
                "Rockenberg", "Special Power Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                12800, 0),
(DEFAULT,"White King Tank", "",
                "Enperry", "Haunt", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                600, 0),
(DEFAULT,"White Layered LS", "",
                "SquidForce", "Special Saver", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                500, 0),
(DEFAULT,"White Sailor Suit", "",
                "Forge", "Ink Saver (Main)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                3000, 0),
(DEFAULT,"White Shirt", "",
                "Splash Mob", "Ink Recovery Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                7500, 0),
(DEFAULT,"White Striped LS", "",
                "Splash Mob", "Quick Respawn", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2300, 0),
(DEFAULT,"White Tee", "",
                "SquidForce", "Ink Saver (Sub)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                400, 0),
(DEFAULT,"White Urchin Rock Tee", "",
                "Rockenberg", "Ink Saver (Main)", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                850, 0),
(DEFAULT,"White V-Neck Tee", "",
                "SquidForce", "Special Saver", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                3800, 0),
(DEFAULT,"Yellow Layered LS", "",
                "SquidForce", "Quick Super Jump", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                500, 0),
(DEFAULT,"Yellow Urban Vest", "",
                "Firefin", "Haunt", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                4100, 0),
(DEFAULT,"Zapfish Satin Jacket", "",
                "Zekko", "Special Charge Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2900, 0),
(DEFAULT,"Zekko Baseball LS", "",
                "Zekko", "Bomb Defense Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                800, 0),
(DEFAULT,"Zekko Hoodie", "",
                "Zekko", "Ninja Squid", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2800, 0),
(DEFAULT,"Zekko Jade Coat", "",
                "Zekko", "Respawn Punisher", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                3600, 0),
(DEFAULT,"Zekko Long Carrot Tee", "",
                "Zekko", "Ink Resistance Up", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1800, 0),
(DEFAULT,"Zekko Long Radish Tee", "",
                "Zekko", "Haunt", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1450, 0),
(DEFAULT,"Zekko Redleaf Coat", "",
                "Zekko", "Haunt", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                2600, 0),
(DEFAULT,"Zink Layered LS", "",
                "Zink", "Respawn Punisher", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                600, 0),
(DEFAULT,"ω-3 Tee", "",
                "Firefin", "Respawn Punisher", "...", "...",
                "F","Clothing",
                "-","-","-","-",
                1200, 0)

INSERT INTO abilities VALUES
  (DEFAULT, "Ability Doubler", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924243/S2_Ability_Ability_Doubler_hu31sq.png"),
  (DEFAULT, "Bomb Defense Up", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924243/S2_Ability_Bomb_Defense_Up_bdujjq.png"),
  (DEFAULT, "Cold-Blooded", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924243/S2_Ability_Cold-Blooded_1_sl5emv.png"),
  (DEFAULT, "Comeback", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924243/S2_Ability_Comeback_iobj5i.png"),
  (DEFAULT, "Drop Roller", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924243/S2_Ability_Drop_Roller_ztgjrb.png"),
  (DEFAULT, "Haunt", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924243/S2_Ability_Haunt_xtgj9e.png"),
  (DEFAULT, "Ink Recovery Up", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924244/S2_Ability_Ink_Recovery_Up_gr8jri.png"),
  (DEFAULT, "Ink Resistance Up", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924243/S2_Ability_Ink_Resistance_Up_v7h9yl.png"),
  (DEFAULT, "Ink Saver (Main)	", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924243/S2_Ability_Ink_Saver__Main_zoigzf.png"),
  (DEFAULT, "Ink Saver (Sub)", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924243/S2_Ability_Ink_Saver__Sub_lh4f8f.png"),
  (DEFAULT, "Last-Ditch Effort", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924243/S2_Ability_Last-Ditch_Effort_udp4va.png"),
  (DEFAULT, "Ninja Squid", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924243/S2_Ability_Ninja_Squid_ds23xf.png"),
  (DEFAULT, "Object Shredder", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924244/S2_Ability_Object_Shredder_rrse8w.png"),
  (DEFAULT, "Opening Gambit", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924244/S2_Ability_Opening_Gambit_u70egr.png"),
  (DEFAULT, "Quick Respawn", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924244/S2_Ability_Quick_Respawn_c4j5sz.png"),
  (DEFAULT, "Quick Super Jump", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924244/S2_Ability_Quick_Super_Jump_ysmavo.png"),
  (DEFAULT, "Respawn Punisher", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924244/S2_Ability_Respawn_Punisher_vewrex.png"),
  (DEFAULT, "Run Speed Up", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924244/S2_Ability_Run_Speed_Up_fnqbon.png"),
  (DEFAULT, "Special Charge Up", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924244/S2_Ability_Special_Charge_Up_bykawt.png"),
  (DEFAULT, "Special Power Up", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924244/S2_Ability_Special_Power_Up_zyfb7r.png"),
  (DEFAULT, "Special Saver", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924244/S2_Ability_Special_Saver_n3rjaz.png"), 
  (DEFAULT, "Stealth Jump", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924244/S2_Ability_Stealth_Jump_pm0zbb.png"),
  (DEFAULT, "Sub Power Up", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924244/S2_Ability_Sub_Power_Up_yn2mbw.png"),
  (DEFAULT, "Swim Speed Up", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924244/S2_Ability_Swim_Speed_Up_cglwie.png"),
  (DEFAULT, "Tenacity", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924245/S2_Ability_Tenacity_zfaehx.png"),
  (DEFAULT, "Thermal Ink", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514924245/S2_Ability_Thermal_Ink_lmepuo.png");

INSERT INTO brands VALUES
  (DEFAULT, "amiibo", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932214/S2_Brand_amiibo_zxtsfg.png", "none", "none"),
  (DEFAULT, "Annaki", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932214/S2_Brand_Annaki_wz8uds.png", " Cold-Blooded", "Special Saver"),
  (DEFAULT, "Cuttlegear", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932214/S2_Brand_Cuttlegear_qxcjxj.png", "none", "none"),
  (DEFAULT, "Enperry", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932214/S2_Brand_Enperry_xzsht4.png", "Sub Power Up", "Ink Resistance Up"),
  (DEFAULT, "Famitsu", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932214/S_Brand_Famitsu_p1hfo0.png", "none", "none"),
  (DEFAULT, "Firefin", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932214/S2_Brand_Firefin_onnvea.png", "Ink Saver (Sub)", "Ink Recovery Up"),
  (DEFAULT, "Forge", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932214/S2_Brand_Forge_capaps.png", "Special Power Up", "Ink Saver (Sub)"),
  (DEFAULT, "Grizzco", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932214/S2_Brand_Grizzco_qsrbcn.png", "none", "none"),
  (DEFAULT, "Inkline", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932214/S2_Brand_Inkline_xyumc0.png", "Bomb Defense Up", "Cold-Blooded"),
  (DEFAULT, "KOG", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932214/S_Brand_KOG_fxklue.png", "none", "none"),
  (DEFAULT, "Krak-On", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932214/S2_Brand_Krak-On_m5nsth.png", "Swim Speed Up", "Bomb Defense Up"),
  (DEFAULT, "Rockenberg", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932214/S2_Brand_Rockenberg_jrwiwx.png", "Run Speed Up", "Swim Speed Up"),
  (DEFAULT, "Skalop", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932214/S2_Brand_Skalop_tjjvui.png", "Quick Respawn", "Special Saver"),
  (DEFAULT, "Splash Mob", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932215/S2_Brand_Splash_Mob_yukqgb.png", "Ink Saver (Main)", "Run Speed Up"),
  (DEFAULT, "SquidForce", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932215/S2_Brand_SquidForce_ze1fag.png", "Ink Resistance Up", "Ink Saver (Main)"),
  (DEFAULT, "Takoroka", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932215/S2_Brand_Takoroka_ycmnbl.png", "Special Charge Up", "Special Power Up"),
  (DEFAULT, "Tentatek", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932215/S2_Brand_Tentatek_tloods.png", "Ink Recovery Up", "Quick Super Jump"),
  (DEFAULT, "The SQUID GIRL", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932215/S2_Brand_Tentatek_tloods.png", "none", "none"),
  (DEFAULT, "Toni Kensa", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932215/S2_Brand_Toni_Kensa_eque1d.png", "Cold-Blooded", "Sub Power Up"),
  (DEFAULT, "Zekko", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932215/S2_Brand_Zekko_oskixp.png", "Special Saver", "Special Charge Up"),
  (DEFAULT, "Zink", "http://res.cloudinary.com/dtvznpuay/image/upload/v1514932215/S2_Brand_Zink_jthryx.png", "Quick Super Jump", "Quick Respawn"),


